
# tasks file for roles/jenkins
- name: install jenkins war file
  get_url:
     url: https://get.jenkins.io/war/2.456/jenkins.war
     dest: /home/saad
- name: run jenkins
  command: /home/saad/jdk-22.0.1/bin/java-jar /home/saad/jenkins.war enable-futue-java
